# Numpy Guide

# Load in NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


# The Basics

In [3]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Syze (in bytes)
a.itemsize

4

In [8]:
# Get Total Size
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [r,c] you can use negative index too
a[1,5]

13

In [11]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [13]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1::2]

array([2, 4, 6])

In [14]:
a[1,5] = 20
a[:,1] = 18
a[:,2] = [22,23]
print(a)

[[ 1 18 22  4  5  6  7]
 [ 8 18 23 11 12 20 14]]


*3d example

In [15]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Get specific element (work outside in)
b[0,1,1]

4

In [17]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [18]:
# All 0s matrix n dimensions
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# All 1s matrix n dimensions
np.ones((2,2),dtype='int32')

array([[1, 1],
       [1, 1]])

In [20]:
# Any other number matrix n dimensions
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [21]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.63502594, 0.28870265],
       [0.0232125 , 0.37415782],
       [0.78244923, 0.1991127 ],
       [0.35410118, 0.64048775]])

In [23]:
# Random Integer values
np.random.randint(6,12, size=(3,3))

array([[ 7,  9,  9],
       [ 6,  9,  6],
       [ 9,  7, 10]])

In [24]:
# The identify matrix
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0 )
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [26]:
my_answer = np.zeros((5,5))
my_answer[:,0] = my_answer[:,-1] = my_answer[0,:] = my_answer[-1,:] = 1
my_answer[int((my_answer.shape[0] -1)/2) , int((my_answer.shape[0] -1)/2)] = 9
print(my_answer)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
answer = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
answer[1:-1,1:-1] = z
print(answer)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### BE CAREFULL WHEN COPYING ARRAYS!!!

In [28]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a,b)

[1 2 3] [100   2   3]


# Mathematics

In [29]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [30]:
a + 2

array([3, 4, 5, 6])

In [31]:
a - 2

array([-1,  0,  1,  2])

In [32]:
a * 2

array([2, 4, 6, 8])

In [33]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [34]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [35]:
a ** 2

array([ 1,  4,  9, 16])

In [36]:
# Take the sin

In [37]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebtra

In [38]:
a = np.ones((2,3),)
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [39]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [40]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Descomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [41]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats, axis=1)

array([1, 4])

In [43]:
np.max(stats, axis=1)

array([3, 6])

In [44]:
np.sum(stats,axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [45]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [47]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous


## Load data from a file

In [52]:
filedata = np.genfromtxt('info.txt',delimiter=",")
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Boolean Masking and Advanced indexing

In [54]:
filedata > 2

array([[False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [55]:
filedata[filedata > 4] 

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
# you can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
f